server.port=${PORT:8080}
spring.application.name=central-backend

# PostgreSQL
#spring.datasource.url=jdbc:postgresql://localhost:5432/offlineupi
#spring.datasource.username=upiuser
#spring.datasource.password=upipass
spring.datasource.driver-class-name=org.postgresql.Driver

#jdbc:postgresql://ep-nameless-salad-aojx00o7-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_nfySV9Ec5ObZ&sslmode=require&channelBinding=require

# Example — use YOUR actual values from Neon
spring.datasource.url=jdbc:postgresql://ep-nameless-salad-aojx00o7-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_nfySV9Ec5ObZ&sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_nfySV9Ec5ObZ

spring.flyway.url=jdbc:postgresql://ep-nameless-salad-aojx00o7-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_nfySV9Ec5ObZ&sslmode=require&channelBinding=require
spring.flyway.user=neondb_owner
spring.flyway.password=npg_nfySV9Ec5ObZ

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Idempotency TTL (24 hours in seconds)
idempotency.ttl.seconds=86400

# Wallet: max offline balance per node (in paise, so 500000 = Rs 5000)
wallet.max.balance.paise=500000

# Freshness window for packets (24 hours in ms)
packet.freshness.window.ms=86400000

# Rate limiting: max requests per edge node per minute
ratelimit.requests.per.minute=60

# Actuator
management.endpoints.web.exposure.include=health,prometheus,metrics
management.endpoint.prometheus.enabled=true

# Logging
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
